name: Generate Contribution Snake

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: vijayhayagrivan2004-creator
          outputs: |
            dist/github-snake.svg?color_snake=%23A65E46&color_dots=%2307203F,%23D9AA90,%23A65E46,%23EBDED4,%23D9AA90
            dist/github-snake-dark.svg?color_snake=%23D9AA90&color_dots=%2307203F,%23A65E46,%23D9AA90,%23EBDED4,%23A65E46
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish generated snake
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
          commit_message: "Update contribution snake"
